### ISSUE TITLE
SCORM files added to publish regardless of whether spoor is enabled at the course level

### ISSUE THREAD

**Issue by davidpesce** [adaptlearning/adapt-contrib-spoor#111]
SCORM files (imsmanifest.xml, scorm_test_harness.html, etc. are all added to the publish file regardless of adding the spoor extension within the course.

**Comment by zenduo** [comment]
Hi have you deleted your build folder and rebuild your course after removing spoor? If spoor isn't installed it shouldn't include any of these files. 

You can remove spoor by running 'adapt uninstall adapt-contrib-spoor'

Does this solve your problem?

Or are you saying if in the config you have disabled it in the json it still includes these files?

**Comment by moloko** [comment]
I would expect these to still be included if you had disabled spoor via config.json. The intention of the `_isEnabled' property is to either temporarily disable spoor (during development, for example) or for if you have a course that needs to go both on an LMS and a web server - so you can switch off SCORM tracking for the web version without having to completely uninstall spoor and rebuild.

**Comment by davidpesce** [comment]
This is via Adapt Builder. I'm not sure on functionality via adapt-cli. 

Spoor wasn't enabled (at the course level) and yet still included those files. 

So, in order to not have the SCORM files included, I'd need to completely uninstall the extension from adapt?

**Comment by moloko** [comment]
Yes that's right, you'd need to completely uninstall the extension (using the plugin manager I think)

To be honest, there's no harm in them being there - they're only ever used at the point you upload the course into an LMS so have no effect otherwise. You'll also be including some JavaScript code that you're not actually using but the overhead of that is pretty slight.

**Comment by davidpesce** [comment]
I think the problem lies when we start implementing other publish standards (xapi, cmi5, xapisec, etc.). If they all drop files in regardless of the course level config, it could get messy fast. 
How hard is it to have it be based on the course config? I'm working on the adapt-xapi extension. I can test it out on that one and then include a PR for the spoor extension.

**Comment by oliverfoster** [comment]
Very much agreed. Need standardise plugin enables/disables and allow the builder to take advantage of including or excluding their output accordingly. Small fix, lots of talk needed.

**Comment by oliverfoster** [comment]
https://adaptlearning.atlassian.net/browse/ABU-1129 < moved to
