### ISSUE TITLE
Consider responding to visibilityChange for mobile platforms for LMSCommit()

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-spoor#115]
This was mentioned by @moloko on the Gitter room in reference to https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility.

"we should be using a combination of pagehide and visibilityChange in Safari mobile & desktop, unload and visibilityChange in Android and just unload for other desktop browsers"

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#873
