### ISSUE TITLE
Is the ReadMe up-to-date?

### ISSUE THREAD

**Issue by zenduo** [adaptlearning/adapt-contrib-spoor#23]
Hey,

Just looking at the read me is this up-to-date? From what I can see now, the 'adapt_insert_tracking_ids' is part of the v1.1. gruntfile.js

Do we just need to update this to give the instructions:

To insert tracking ID's on your course, run the following command:
$ grunt adapt_insert_tracking_ids

**Comment by moloko** [comment]
have completely re-written the README, should be accurate now
