### ISSUE TITLE
Uglifying source build/offline_API_wrapper.js failed

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-spoor#259]
### Subject of the issue/enhancement/features
When building a new course, the uglify task fails with the following message:

```
Uglifying source build/offline_API_wrapper.js failed
Warning: Uglification failed.
Unexpected token: punc «.».
Line 79 in build/offline_API_wrapper.js
```

### Your environment
* Framework 5.24.4
* Spoor 5.5.3

### Steps to reproduce
1. Install a new course with `adapt create course`
2. cd to the new directory
3. Run `grunt build`

### Expected behaviour
Successful build

### Actual behaviour
Uglification task fails.

### Potential cause
I believe it was caused by commit [479c2d](https://github.com/adaptlearning/adapt-contrib-spoor/commit/479c2d143a2a8ec94ea742d123f135a4c6bdc80e).  In `required/offline_API_wrapper.js`, lines 79 and 133 use the ES6 style Optional Chaining feature.

**Comment by oliverfoster** [comment]
Will need to bump the fw version required by spoor once the above pr is in.
