### ISSUE TITLE
Loss of Connection Notification feature

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt-contrib-spoor#268]
### Subject of the feature
Many Learning Management Systems fall short of informing learners of a connection loss which leads to missing or incomplete data for many users. Would like to include a notify message once connection issues occur, which will help users to correct SCORM progress issues as they occur.

### Expected behaviour
A notify pop-up should occur at the point the connection between Adapt and the LMS fails. We cannot fully trust the SCORM API to give factual connection issues, so the proposal would be to test the connection to the server instead.

### Actual behaviour
Currently, little is done within Adapt to help users troubleshoot connection issues once they occur.

**Comment by joe-replin** [comment]
Closed current PR. A new one will be opened later this week.

**Comment by cahirodoherty-learningpool** [comment]
Hi Joe, is this something that you imagine could be worked into the xAPI extension also?

**Comment by danielghost** [comment]
@cahirodoherty-learningpool - Unlike SCORM, xAPI already uses HTTP methods when transferring data, so a connection test isn't required like it is for spoor, but the xAPI plugin could hook into the event driven model of the new [trackingErrors](https://github.com/adaptlearning/adapt-contrib-trackingErrors) plugin to handle the UI and ability to retry failed data transmissions.
