### ISSUE TITLE
Issue with SPOOR error Handling message

### ISSUE THREAD

**Issue by lokeshece1** [adaptlearning/adapt-contrib-spoor#283]
### Undefined spoor configuration error for ScormError

Describe your issue here.

Symptom: Adapt shows endless loop of the the loading screen
Console Error: Seems to be stuck on the cmi.core.lesson_status

### Your environment
* version (Framework 5.31.10) 
* which browser and its version - Chrome
* device(s) + operating system(s) - windows 10

### Steps to reproduce
Check with latest Spoor extension (5.7.0) with different LMS platform

### Expected behaviour
It should first check whether Adapt is enabled then check for the course configuration.
Return early added to wrapper.js if Adapt.course does not exist

[adapt-contrib-spoor/js/scorm/wrapper.js] 
if (!Adapt.course) return;

### Screenshots (if you can)
![image](https://github.com/adaptlearning/adapt-contrib-spoor/assets/35100121/400268bc-56a8-4f2c-873b-8b4afd497cc3)

![image](https://github.com/adaptlearning/adapt-contrib-spoor/assets/35100121/f4222f30-dd1a-4e6a-b472-0de9ef81ebc1)

**Comment by oliverfoster** [comment]
fixed with https://github.com/adaptlearning/adapt-contrib-spoor/pull/301
