### ISSUE TITLE
Attempt to getInteractionCount on LMS that doesn't support this SCORM 1.2 feature

### ISSUE THREAD

**Issue by paulstevendev** [adaptlearning/adapt-contrib-spoor#294]
I am seeing an issue on an LMS where an error dialogue is displaying after sumitting a question. 

![image](https://github.com/adaptlearning/adapt-contrib-spoor/assets/114067294/f53ce8f2-cd08-424c-9fca-6c877866d7d1)

Looking at the code I can see it is calling this.scorm.getInteractionCount() inside the onQuestionRecordInteraction function within adapt-stateful-session.js

So it would appear this code does not have any check to see if the LMS supports cmi.interaction._count

I am getting the error every time I answer a question. It is possibly an issue with this particular LMS but it is the only LMS we use that does not have this optional SCORM 1.2 element. So it would be good to hear if anyone else has tested this on an LMS that does not support cmi.interactions._count

https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/adapt-stateful-session.js#L205C2-L220C4

**Comment by oliverfoster** [comment]
The quoted lines, call `offlineStorage.set('interaction', id, response, result, latency, responseType); `:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/adapt-stateful-session.js#L205-L220

Which is calling `recordInteraction`:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/adapt-offlineStorage-scorm.js#L111-L133

Which is calling `isSupported`, `if (!this.isSupported('cmi.interactions._count')) { `:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/scorm/wrapper.js#L366-L392

`isSupported` calls `get`:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/scorm/wrapper.js#L475-L490

`getValue` is called here:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/libraries/SCORM_API_wrapper.js#L483-L505

Your error is triggering here: 
https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/scorm/wrapper.js#L396-L421

This is your error:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/scorm/error.js#L29

**Comment by paulstevendev** [comment]
Surely this code is not checking isSupported('cmi.interactions._count')

https://github.com/adaptlearning/adapt-contrib-spoor/blob/f07a6032a687b6653c4dbcd903797663fa3ec665/js/adapt-stateful-session.js#L213C1-L215C34

**Comment by oliverfoster** [comment]
Yup, agreed. Needs a `if (!this.scorm.isSupported('cmi.interactions._count')) return` above that line?

**Comment by paulstevendev** [comment]
That is exactly what I have done and testing as we speak

**Comment by paulstevendev** [comment]
@oliverfoster happy to create a PR for this.

Not done this before so just checking the procedure

Do I create a local branch issue/294 and then push this up (I don't appear to have permission to do so)

Then create a PR

**Comment by oliverfoster** [comment]
You can fork the repo, create your issue/294 and then push from there.

**Comment by paulstevendev** [comment]
Done
