### ISSUE TITLE
Possible issue if course.json does not contain "_spoor" element

### ISSUE THREAD

**Issue by paulstevendev** [adaptlearning/adapt-contrib-spoor#299]
When testing in the authoring tool using the latest adapt-contrib-spoor I do not see any reference to "_spoor" in the course.json file of the published SCORM zip file.

Therefore I question whether this is going to cause an issue here:

`const config = Adapt.course.get('_spoor');`

https://github.com/adaptlearning/adapt-contrib-spoor/blob/4370780b00d734819159acb866ace308d5ec59f0/js/scorm/wrapper.js#L549C1-L551C74

The code will hang here surely if there is no "_spoor" element present in course.json

**Comment by paulstevendev** [comment]
Possibly related to this issue
https://github.com/adaptlearning/adapt-contrib-spoor/issues/283

**Comment by paulstevendev** [comment]
[course.json](https://github.com/adaptlearning/adapt-contrib-spoor/files/13646739/course.json)
Attached course.json from published course from open source authoring tool using Spoor 5.9.3 and the following
Adapt authoring tool 0.11.2.
Adapt framework v5.33.4
You will see there is no "_spoor" element in course.json

**Comment by oliverfoster** [comment]
Confirmed working with no _spoor in course.json now.
