### ISSUE TITLE
Automated test for SCORM 1.2 compatibility

### ISSUE THREAD

**Issue by cajones** [adaptlearning/adapt-contrib-spoor#31]
1) Given i have a course with an assessment and I'm tracking _only_ assessment completion when I pass the assessment then the lesson_status should be either "completed" or "passed".

2) Given i have a course with an assessment and I'm tracking assessment completion _and_ course completion when I pass the assessment _and_ complete all the blocks then the lesson_status should be either "completed" or "passed"

3) Given i have a course without an assessment and I'm tracking course completion when I   complete all the blocks then the lesson_status should be either "completed" or "passed"

**Comment by taylortom** [comment]
This is implemented, will be tested during code freeze.
