### ISSUE TITLE
main.html

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-spoor#39]
This should either be renamed to something that makes it more obvious what it is - or removed completely. At the moment people are accidentally using it to run the course- which then causes unexpected behaviour (such as the content not being responsive).

**Comment by LukaszGrela** [comment]
+1 for renaming

**Comment by brian-learningpool** [comment]
+1 for renaming, although there will be an associated change required in the framework.  Maybe as part of version 2.0?

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-484
