### ISSUE TITLE
spoor tries to get _onAssessmentFailure string, Adapt's config only has _onQuizFailure

### ISSUE THREAD

**Issue by GavinNelson** [adaptlearning/adapt-contrib-spoor#40]
around line 103 of adapt-contrib-spoor.js spoor tries to get this.data._reporting._onAssessmentFailure but in the framework's config.json the string is called _onQuizFailure. this results in the error
cmi.core.lesson_status of undefined is not supported.

this has already been mentioned in #25 

off topic: apologies if i'm doing this wrong, this is my first git issue submission

**Comment by moloko** [comment]
now fixed in the master branch too
