### ISSUE TITLE
undefined is not a function error on CourseComplete

### ISSUE THREAD

**Issue by cajones** [adaptlearning/adapt-contrib-spoor#44]
Uncaught TypeError: undefined is not a function        adapt.min.js:128
(anonymous function)                                                  adapt.min.js:117
(anonymous function)

see [original conversation](https://community.adaptlearning.org/mod/forum/discuss.php?d=412)

**Comment by zenduo** [comment]
Moved to  https://adaptlearning.atlassian.net/browse/ABU-483
