### ISSUE TITLE
Add ability to disable spoor via config.json.

### ISSUE THREAD

**Issue by JeromeLam** [adaptlearning/adapt-contrib-spoor#49]
The "_isEnabled" property was added to *adapt-contrib-spoor/properties.schema* but it isn't used anywhere.

Checking for it in the plugin would allow us to disable adapt-contrib-spoor without uninstalling it.

**Comment by oliverfoster** [comment]
+1 Jerome @ can you make a PR for this?  Just add:

```
if ( this.data._isEnabled === false) return;
```

Under this line:

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L24

**Comment by moloko** [comment]
definitely a great idea - but you might have to add in more code than that. 

I'd have thought that you'd have to add in a check every time there's a call to scormWrapper.*doSomething*()

if that turns out to be the case then probably best to add an _isEnabled variable to adapt-contrib.spoor so that you don't have to keep doing if ( this.data._isEnabled === false) or if ( this.data._isEnabled === true)

I don't mind looking into doing this if @JeromeLam doesn't have time/doesn't want to

**Comment by JeromeLam** [comment]
Actually, I'd be very interested in pursuing this issue as a learning lesson both for using Git (for the first time!) and contributing to Adapt.

In my local build, I had added
```javascript
if (!this.data._isEnabled) return;
```
exactly where Oliver suggested and that worked fine for me.  I figured that if *onDataReady* wasn't called, the event listeners would never be attached and *scormWrapper.function()* would never get called.

Please let me know if my statement above makes sense.  Also, I wouldn't mind hints as to the process of making the PR.  Do I have to specify which branch the change would go under?

**Comment by oliverfoster** [comment]
Rough process: Fork the repo, branch in your fork from the develop to a branch called 'feature-isenabled', make your changes in that branch and PR back to the adaptlearning/adapt-contrib-spoor develop branch. After the PR you can then delete your feature branch and/or fork, unless you plan to make further changes. That way you can always keep your develop branch clean and so be able to sync it with adaptlearning's base.

**Comment by oliverfoster** [comment]
The code above should work with the components in adaptlearning core as you've described. With more complicated extensions that make direct use of the scormwrapper Matt's answer is more appropriate.

**Comment by moloko** [comment]
@JeromeLam certainly does make sense, thanks

**Comment by JeromeLam** [comment]
Thanks @oliverfoster for the PR suggested process.  It's been submitted.

We can revisit the case of complicated extensions that use scormWrapper directly when it comes up.  However, based on how I understand adapt-contrib-spoor.js, I don't believe any of the Spoor functions can be called directly since we're dealing with a throw-away instance.   As for scormWrapper.js, anyone requiring it directly will be re-creating their own Spoor class.  I feel this case won't happen anytime soon.

**Comment by moloko** [comment]
this is now done in master
