### ISSUE TITLE
Spoor generates an error that _isEnabled is not defined

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-spoor#53]
Old courses will not have an isEnabled property.

Some defensive programming is required on this line:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L25

**Comment by moloko** [comment]
good call!

**Comment by oliverfoster** [comment]
That's fine as it is. _isEnabled must be set to false for it to be turned off. Any other value, including undefined will keep it enabled.

**Comment by oliverfoster** [comment]
If the config.json spoor attribute is not set, this will definitely throw an error.

**Comment by moloko** [comment]
might still generate a JavaScript error though - is that what you're saying @brian-learningpool ? If so, which browser?

**Comment by dennis-learningpool** [comment]
Hi @oliverfoster, @moloko - this currently presents a Javascript error when you preview content in the Authoring Tool if you have not enabled the spoor extension.

I have pushed a suggested fix for it here: https://github.com/adaptlearning/adapt-contrib-spoor/commit/fa8e5ea4685b97f7a0e0a39aa9ec73ea48db9808

**Comment by dennis-learningpool** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-spoor/pull/54
