### ISSUE TITLE
IE9 - SCORM tracking test of 'just pass quiz' version

### ISSUE THREAD

**Issue by kineotest** [adaptlearning/adapt-contrib-spoor#6]
Completed quiz, failed - LMS (moodle 1.9) correctly recorded incomplete status and failing score

Exited module, re-entered - when I went into the quiz page, it was entirely blank except for the top nav bar

**Comment by moloko** [comment]
I'm not sure what happened here but this has never been reported since. Will close since we will soon be retesting for v2 anyway.
