### ISSUE TITLE
grunt tracking-insert does not add tracking from 0

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt-contrib-spoor#65]
The grunt tracking-insert command does not start from 0 in some cases. If we have the entries from 0 it abruptly jumps to a number and starts incrementing the tracking IDs from there instead of from 0.

To work around this issue, we had to delete all the tracking ID entries from the files and re-execute the command to get the tracking IDs in order.

**Comment by oliverfoster** [comment]
Can we see if the tracking reset and tracking remove functions are available from the tracking library to turn into grunt commands?

**Comment by aniketdharia** [comment]
It's there in the code but not part of the grunt file.

**Comment by taylortom** [comment]
They should all be loaded here: https://github.com/adaptlearning/adapt_framework/blob/develop/Gruntfile.js#L565

The insert task is supposed to add additional tracking ids, not start from 0.

**Comment by oliverfoster** [comment]
the are excluded here https://github.com/adaptlearning/adapt_framework/blob/develop/Gruntfile.js#L538-L540

**Comment by taylortom** [comment]
That's just for the help command (i.e. what's written out)

**Comment by oliverfoster** [comment]
i see, can we do the old tracking-insert > adapt_insert_tracking_ids, tracking-remove > adapt_remote_tracking_ids and tracking-reset > adapt_reset_trackings_ids ?

**Comment by taylortom** [comment]
Nope, we'd need to register new tasks/rename the existing ones.

**Comment by aniketdharia** [comment]
Yes agreed but then how do we run the reset command? Its not there in the documentation.

**Comment by taylortom** [comment]
To use the tasks, you need to set up something like the following: [master/Gruntfile.js#L367-L372](https://github.com/adaptlearning/adapt_framework/blob/master/Gruntfile.js#L367-L372).

I don't think that the insert task is very useful tbh; it makes more sense to me to reset the IDs each time.

**Comment by aniketdharia** [comment]
:+1:  For reset IDs and then execute the insert.

**Comment by taylortom** [comment]
Have added the tasks to https://github.com/adaptlearning/adapt_framework/pull/613.

I had also previously added the tracking-insert task to the build/dev tasks, so this happens automatically. Do we want to switch this for the reset task?

https://github.com/taylortom/adapt_framework/blob/grunt-update/Gruntfile.js#L566

**Comment by oliverfoster** [comment]
i think leaving tracking-insert as the build/dev task is the least damaging. (as far as i understand it) courses can be patched after they have been distributed, so the ids have to remain consistent

**Comment by aniketdharia** [comment]
Any progress?

**Comment by taylortom** [comment]
Fixed in https://github.com/adaptlearning/adapt_framework/pull/624
