### ISSUE TITLE
bug: missing 'this.'

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-spoor#67]
https://github.com/adaptlearning/adapt-contrib-spoor/blob/develop/js/adapt-stateful-session.js#L95

**Comment by moloko** [comment]
I can sort this out as was just about to commit some stuff to develop (I may have already done it)

**Comment by moloko** [comment]
just checked and I have already fixed this in the code I'm going to commit

**Comment by oliverfoster** [comment]
Cool
