### ISSUE TITLE
Defensive programming missing from adapt-stateful-session.js

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-spoor#98]
The code in the following line doesn't check that the spoor plugin is actually enabled on a course.  There should possibly be a `.has()` call here.
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-stateful-session.js#L24

This manifests itself in errors by default in the authoring tool

**Comment by oliverfoster** [comment]
Cool
